"""
Convert Stretch teleop recordings into a LeRobot v2 parquet dataset.

Input format:
- dataset generated by demo_record/robot_teleop_ui_ros_v2.py (JSONL + MP4 + meta)

Output format:
- LeRobot v2 dataset with parquet episodes (compatible with OpenPI training loaders)

Example:
UV_CACHE_DIR=/tmp/uv-cache uv run examples/stretch/convert_stretch_recordings_to_lerobot.py \
  --source-root dataset/stretch_recordings \
  --output-root dataset \
  --output-repo-id stretch_libero_like
"""

from __future__ import annotations

import json
from pathlib import Path
import shutil

import cv2
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
import numpy as np
import tyro


def _read_jsonl(path: Path) -> list[dict]:
    items: list[dict] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Standard json.loads accepts NaN values (used by source recordings).
            items.append(json.loads(line))
    return items


def _coerce_vector(values: list[float] | np.ndarray, dim: int) -> np.ndarray:
    arr = np.asarray(values, dtype=np.float32).reshape(-1)
    if arr.shape[0] < dim:
        arr = np.pad(arr, (0, dim - arr.shape[0]), mode="constant")
    elif arr.shape[0] > dim:
        arr = arr[:dim]
    # Replace NaN/inf with finite values so parquet stats + normalization are stable.
    return np.nan_to_num(arr, nan=0.0, posinf=0.0, neginf=0.0)


def _detect_action_dim(source: Path) -> int:
    episodes = _read_jsonl(source / "meta" / "episodes.jsonl")
    episodes = sorted(episodes, key=lambda x: x["episode_index"])
    for ep in episodes:
        data_path = source / ep["data_path"]
        if not data_path.exists():
            continue
        rows = _read_jsonl(data_path)
        for row in rows:
            action = row.get("action", [])
            if action is not None:
                dim = int(np.asarray(action).reshape(-1).shape[0])
                if dim > 0:
                    return dim
    raise RuntimeError("Could not detect action dimension from source recordings.")


def _open_video(path: Path) -> cv2.VideoCapture:
    cap = cv2.VideoCapture(str(path))
    if not cap.isOpened():
        raise RuntimeError(f"Failed to open video: {path}")
    return cap


def _read_rgb_frame(cap: cv2.VideoCapture, *, resize_hw: tuple[int, int] | None) -> np.ndarray:
    ok, frame_bgr = cap.read()
    if not ok:
        raise RuntimeError("Video ended earlier than expected.")
    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    if resize_hw is not None:
        h, w = resize_hw
        frame_rgb = cv2.resize(frame_rgb, (w, h), interpolation=cv2.INTER_AREA)
    return frame_rgb


def main(
    source_root: str = "dataset/stretch_recordings",
    output_root: str = "dataset",
    output_repo_id: str = "stretch_libero_like",
    *,
    robot_type: str = "stretch3",
    state_dim: int = 8,
    action_dim: int | None = None,
    image_size: int = 256,
    fps: int | None = None,
    max_episodes: int | None = None,
    overwrite: bool = True,
):
    source = Path(source_root).expanduser().resolve()
    out_root = Path(output_root).expanduser().resolve()
    out_dir = out_root / output_repo_id

    if overwrite and out_dir.exists():
        shutil.rmtree(out_dir)

    info = json.loads((source / "meta" / "info.json").read_text(encoding="utf-8"))
    source_fps = int(round(float(info.get("fps", 6))))
    target_fps = int(fps if fps is not None else source_fps)
    resize_hw = (image_size, image_size) if image_size > 0 else None
    if action_dim is None:
        action_dim = _detect_action_dim(source)
        print(f"[info] detected action_dim={action_dim}")

    features = {
        # Match Libero-style keys expected by LeRobotLiberoDataConfig.
        "image": {"dtype": "image", "shape": (image_size, image_size, 3), "names": ["height", "width", "channel"]},
        "wrist_image": {
            "dtype": "image",
            "shape": (image_size, image_size, 3),
            "names": ["height", "width", "channel"],
        },
        "state": {"dtype": "float32", "shape": (state_dim,), "names": ["state"]},
        "actions": {"dtype": "float32", "shape": (int(action_dim),), "names": ["actions"]},
    }

    dataset = LeRobotDataset.create(
        repo_id=output_repo_id,
        root=out_dir,
        robot_type=robot_type,
        fps=target_fps,
        features=features,
        use_videos=False,
    )

    episodes = _read_jsonl(source / "meta" / "episodes.jsonl")
    episodes = sorted(episodes, key=lambda x: x["episode_index"])
    if max_episodes is not None:
        episodes = episodes[:max_episodes]

    converted_frames = 0
    for ep in episodes:
        ep_idx = int(ep["episode_index"])
        task = str(ep.get("task", "unspecified_task"))

        rows = _read_jsonl(source / ep["data_path"])
        if not rows:
            print(f"[skip] episode {ep_idx:06d}: no rows")
            continue

        head_video = source / ep["videos"]["head_rgb"]
        wrist_video = source / ep["videos"]["wrist_rgb"]
        cap_head = _open_video(head_video)
        cap_wrist = _open_video(wrist_video)

        try:
            for row in rows:
                head_img = _read_rgb_frame(cap_head, resize_hw=resize_hw)
                wrist_img = _read_rgb_frame(cap_wrist, resize_hw=resize_hw)

                frame = {
                    "image": head_img,
                    "wrist_image": wrist_img,
                    "state": _coerce_vector(row.get("observation.state", []), state_dim),
                    "actions": _coerce_vector(row.get("action", []), action_dim),
                    "task": task,
                }
                dataset.add_frame(frame)
                converted_frames += 1

            dataset.save_episode()
        finally:
            cap_head.release()
            cap_wrist.release()

        print(f"[ok] episode {ep_idx:06d}: {len(rows)} frames")

    print(f"\nDone. Wrote {len(episodes)} episodes / {converted_frames} frames to: {out_dir}")


if __name__ == "__main__":
    tyro.cli(main)

# uv run examples/stretch/convert_stretch_recordings_to_lerobot.py \
#   --source-root dataset/stretch_recordings \
#   --output-root dataset \
#   --output-repo-id stretch_recordings_pi \
#   --action-dim 10


# uv run examples/convert_jax_model_to_pytorch.py \
#   --config_name pi05_libero \
#   --checkpoint_dir gs://openpi-assets/checkpoints/pi05_base/ \
#   --output_path /data/ibk5106/robotics/policies/openpi/checkpoints/pi05_base_pytorch

# export HF_LEROBOT_HOME=/data/ibk5106/robotics/policies/openpi/dataset

# uv run scripts/compute_norm_stats.py --config-name pi05_stretch

# XLA_PYTHON_CLIENT_MEM_FRACTION=0.9 uv run scripts/train.py pi05_stretch --exp-name=stretch3_experiment --overwrite

# uv run scripts/compute_norm_stats_safe.py --config-name pi05_stretch_low_mem_finetune



"""
XLA_PYTHON_CLIENT_MEM_FRACTION=0.8 \
uv run scripts/train.py pi05_stretch_low_mem_finetune \
  --exp-name=stretch3_experiment \
  --overwrite \
  --batch-size=4

XLA_PYTHON_CLIENT_MEM_FRACTION=0.8 \
uv run scripts/train.py pi0_libero_low_mem_finetune \
  --exp-name=libero_lora_pi0_test \
  --overwrite \
  --batch-size=16

uv run examples/stretch/convert_stretch_recordings_to_lerobot_delta.py \
  --source-root dataset/stretch_recordings_v2 \
  --output-root dataset \
  --output-repo-id stretch_recordings_v2_pi_delta \
  --action-dim 10


"""